### DISCUSSION TITLE
Configurable commands

### DISCUSSION THREAD

**Discussion by mja8020** [mja8020/templar#17] [Ideas]
Given a config like the following
```yaml
commands:
  plan: terraform plan
  apply: terraform apply
  build: docker build --tag  {{ .SomeVariable }}
```

You could then run something like this
```bash
templar run plan
templar run apply --include=all
```

This would give some optional IAC type capability but keep it tool agnostic

@iezell I think this is what we had discussed?
@terrabyteian Thoughts
